### ISSUE TITLE
'import _fs$ from "https://cdn.esm.sh/v15/_node_fs.js"'

### ISSUE THREAD

**Issue by mggower** [crewdevio/vue-deno-compiler#4]
'import _fs$ from "https://cdn.esm.sh/v15/_node_fs.js"' has no export named 'default' 

runtime error

in postcss/postcss.js (6:8)

**Comment by buttercubz** [comment]
> 'import _fs$ from "https://cdn.esm.sh/v15/_node_fs.js"' has no export named 'default'
> 
> runtime error
> 
> in postcss/postcss.js (6:8)

seems like a esm.sh error i will check this asap

**Comment by ije** [comment]
@mggower `deno --reload=https://esm.sh run ...` should fix this, since esm.sh updated the deno polyfill to `std/node`

**Comment by ije** [comment]
use deno.land/x/postcss instead of esm.sh? or update esm.sh v15 to v21...sorry the breaking change of esm.sh

**Comment by buttercubz** [comment]
fixed
